Repository LightJack05/AnonKey-Backend, pull requests merged in 2025-01, with the labels that each got.

#99 Fixed project formatting
  ApiEndpoints/Folders/Create.cs
  ApiEndpoints/Folders/Update.cs
Labels: enhancement

#101 Added graphviz instruction to readme
  README.md
Labels: documentation

#102 Added maja to license
  LICENSE
Labels: documentation

#98 Added more CI checks to GH Actions
  .github/workflows/build.yml
  .github/workflows/formatting-check.yml
  .github/workflows/test.yml
  .github/workflows/warnings.yml
Labels: enhancement

#105 Added token type and UUID to token claims
  ApiEndpoints/Authentication/Login.cs
  ApiEndpoints/Users/Create.cs
  Authentication/TokenService.cs
Labels: enhancement

#107 Test data
  Development/SampleData.cs
Labels: enhancement

#106 Added expiry and parent to token claims
  Authentication/TokenService.cs
Labels: enhancement

#108 Added revoked tokens table
  Data/DatabaseHandle.cs
  Models/Token.cs
Labels: enhancement

#109 Fixed multiple warnings
  ApiDatastructures/Credentials/GetCredential/CredentialsGetCredential.cs
  ApiDatastructures/Credentials/GetCredential/CredentialsGetResponseBody.cs
  ApiDatastructures/Folders/GetFolder/FoldersGetFolder.cs
  ApiDatastructures/Folders/GetFolder/FoldersGetResponseBody.cs
  ApiDatastructures/RequestError/ErrorResponseBody.cs
  ApiDatastructures/Users/GetUser/UsersGetResponseBody.cs
  ApiDatastructures/Users/GetUser/UsersGetUser.cs
  ApiEndpoints/Authentication/ChangePassword.cs
  ApiEndpoints/Authentication/Login.cs
  ApiEndpoints/Credentials/Create.cs
  ApiEndpoints/Credentials/Delete.cs
  ApiEndpoints/Credentials/EndpointSetup.cs
  ApiEndpoints/Credentials/GetAll.cs
  ApiEndpoints/Credentials/GetCredential.cs
  ApiEndpoints/Credentials/SoftDelete.cs
  ApiEndpoints/Credentials/SoftUndelete.cs
  ApiEndpoints/Credentials/Update.cs
  ApiEndpoints/Folders/Create.cs
  ApiEndpoints/Folders/Delete.cs
  ApiEndpoints/Folders/EndpointSetup.cs
  ApiEndpoints/Folders/GetAll.cs
  ApiEndpoints/Folders/GetFolder.cs
  ApiEndpoints/Folders/Update.cs
  ApiEndpoints/Users/Create.cs
  ApiEndpoints/Users/Delete.cs
  ApiEndpoints/Users/EndpointSetup.cs
  ApiEndpoints/Users/GetUser.cs
  ApiEndpoints/Users/Update.cs
  ApiEndpoints/Uuid/NewUuid.cs
  Data/DatabaseHandle.cs
Labels: enhancement

#110 Redesigned login system
  .gitignore
  ApiDatastructures/Authentication/Login/AuthenticationLoginResponseBody.cs
  ApiDatastructures/Authentication/Login/AuthenticationLoginToken.cs
  ApiDatastructures/Users/Create/UsersCreateResponseBody.cs
  ApiDatastructures/Users/Create/UsersCreateResponseToken.cs
  ApiEndpoints/Authentication/ChangePassword.cs
  ApiEndpoints/Authentication/Login.cs
  ApiEndpoints/Credentials/Create.cs
  ApiEndpoints/Credentials/Delete.cs
  ApiEndpoints/Credentials/GetAll.cs
  ApiEndpoints/Credentials/GetCredential.cs
  ApiEndpoints/Credentials/SoftDelete.cs
  ApiEndpoints/Credentials/SoftUndelete.cs
  ApiEndpoints/Credentials/Update.cs
  ApiEndpoints/Folders/Create.cs
  ApiEndpoints/Folders/Delete.cs
  ApiEndpoints/Folders/GetAll.cs
  ApiEndpoints/Folders/GetFolder.cs
  ApiEndpoints/Folders/Update.cs
  ApiEndpoints/Users/Create.cs
  ApiEndpoints/Users/Delete.cs
  ApiEndpoints/Users/GetUser.cs
  ApiEndpoints/Users/Update.cs
  ApiEndpoints/Uuid/NewUuid.cs
  Authentication/TokenActions.cs
  Authentication/TokenService.cs
  Data/DatabaseHandle.cs
  Models/Token.cs
Labels: enhancement

#112 Added nullcheck and refactored two
  Authentication/TokenService.cs
Labels: enhancement

#113 Added logout endpoint
  ApiEndpoints/Authentication/EndpointSetup.cs
  ApiEndpoints/Authentication/Logout.cs
Labels: enhancement

#118 Fixed logout endpoint documentation
  ApiEndpoints/Authentication/Logout.cs
Labels: documentation

#119 Added Database scrubbing
  Program.cs
  Services/DatabaseCleanup.cs
Labels: enhancement

#120 Added refresh endpoint for access token
  ApiDatastructures/Authentication/RefreshAccessToken/AuthenticationRefreshAccessToken.cs
  ApiDatastructures/Authentication/RefreshAccessToken/AuthenticationRefreshAccessTokenResponseBody.cs
  ApiEndpoints/Authentication/EndpointSetup.cs
  ApiEndpoints/Authentication/RefreshEndpointAccessToken.cs
Labels: enhancement

#122 Added ensure created to database cleanup
  Services/DatabaseCleanup.cs
Labels: bug
